# Spring properties
spring:
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: false
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://ec2-52-23-14-156.compute-1.amazonaws.com:5432/dd0407kq4t5co9
    driver-class-name: org.postgresql.Driver
    username: nvitwwvclmktgw
    password: 8856370a2c353d144fd18f1c556c9b82250e036a4de34c63838977b9cda783df
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5

logging:
  level:
    root: INFO
    org.springframework: ERROR